# pylint: skip-file
# Generated by Django 4.2.11 on 2024-05-03 18:46

import django.db.models.deletion
import django.contrib.postgres.fields.jsonb

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(max_length=4096)),
                ('name', models.TextField(max_length=4096)),
                ('refresh_interval', models.DurationField()),
                ('next_run', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DashboardSignalValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded', models.DateTimeField()),
                ('value', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_values', to='simple_dashboard.dashboardsignal')),
            ],
        ),
    ]
