# pylint: skip-file
# Generated by Django 4.2.11 on 2024-05-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardsignal',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dashboardsignal',
            name='configuration',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='dashboardsignal',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
