# Generated by Django 4.2.11 on 2024-05-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_dashboard', '0002_dashboardsignal_active_dashboardsignal_configuration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardsignal',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
