# pylint: skip-file
# Generated by Django 4.2.11 on 2024-05-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_dashboard', '0004_alter_dashboardsignal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardsignal',
            name='configuration',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
