# pylint: skip-file
# Generated by Django 4.2.13 on 2024-06-21 18:40

import sys

import django.core.serializers.json
from django.db import migrations, models

if sys.version_info[0] > 2:
    from django.db.models import JSONField # pylint: disable=no-name-in-module
else:
    from django.contrib.postgres.fields import JSONField

class Migration(migrations.Migration):

    dependencies = [
        ('simple_dashboard', '0006_alter_dashboardsignal_configuration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardsignal',
            name='configuration',
            field=JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardsignalvalue',
            name='value',
            field=JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
